Repository ChildMindInstitute/mindlogger-web-refactor, pull requests merged in 2023-10, with the labels that each got.

#241 [M2-2801] Fix: subscript markdown
  src/shared/ui/Markdown/lib/markdown-builder.ts
Labels: Bug, Done

#242 [M2-2801] Fix: subscript markdown
  src/shared/ui/Markdown/lib/markdown-builder.ts
Labels: Bug, Done

#244 [M2-2831] Fix: responseIsEditable
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
Labels: Bug, Done

#243 [M2-2831] Fix: responseIsEditable
  src/entities/activity/ui/ActivityItemStepper.tsx
  src/widgets/ActivityDetails/ui/ActivityItemList.tsx
Labels: Bug, Done

#245 fix: applet details layout
  src/widgets/ActivityGroups/ui/ActivityGroupList.tsx
Labels: Bug, Done

#247 [M2-2799] Fix: highlighted text markdown
  src/shared/ui/Markdown/lib/markdown-builder.ts
Labels: Bug, Done

#246 [M2-2799] Fix: highlighted text markdown
  src/shared/ui/Markdown/lib/markdown-builder.ts
Labels: Bug, Done

#248 [M2-3503] Fix: translation
  src/i18n/fr/translation.json
Labels: Bug, Done

#249 [M2-2307] Fix: min-width modal
  src/widgets/Modal/ui/style.scss
Labels: Bug, Done

#250 [M2-3702] Fix: Conditional logic
  src/entities/activity/model/hooks/useActivityEventProgressState.ts
  src/entities/activity/ui/ActivityItemStepper.tsx
  src/widgets/ActivityDetails/ui/ActivityItemList.tsx
Labels: Bug, Done

#253 [M2-3708] Fix: numeric only
  src/entities/activity/ui/items/TextItem.tsx
  src/i18n/en/translation.json
  src/i18n/fr/translation.json
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
Labels: Bug, Done

#254 [M2-3712] Fix: default font size 16px
  src/app/index.css
  src/features/ForgotPassword/ui/ForgotPasswordForm.tsx
  src/features/Login/ui/LoginForm.tsx
  src/features/SaveAssessmentAndExit/index.tsx
  src/pages/Login/index.tsx
  src/pages/Signup/index.tsx
  src/shared/ui/BaseButton/index.tsx
Labels: Bug, Done

#255 [M2-3710] Fix: login after signup success
  src/entities/user/model/hooks/index.ts
  src/entities/user/model/hooks/useOnLogin.ts
  src/features/Login/ui/LoginForm.tsx
  src/features/Signup/ui/SignupForm.tsx
Labels: Bug, Done

#256 [M2-3713] Fix: assessment layout align
  src/shared/ui/CardItem/CardItem.tsx
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
Labels: Bug, Done

#192 M2 3002 add mixpanel events
  package.json
  src/app/Main.tsx
  src/entities/activity/lib/markdownVariableReplacer.ts
  src/entities/applet/ui/AppletCard.tsx
  src/features/InvitationAccept/ui/InvitationAcceptButton.tsx
  src/features/Login/ui/LoginForm.tsx
  src/features/Logout/lib/useLogout.ts
  src/features/PrivateJoinAccept/ui/PrivateJoinAcceptButton.tsx
  src/features/Signup/ui/SignupForm.tsx
  src/pages/Dashboard/ui/index.tsx
  src/pages/Login/ui/index.tsx
  src/pages/Signup/ui/index.tsx
  src/shared/utils/encryption/encryption.ts
  src/shared/utils/index.ts
  src/shared/utils/mixpanel.ts
  src/widgets/ActivityDetails/ui/ActivityItemList.tsx
  src/widgets/ActivityGroups/ui/ActivityGroupList.tsx
  src/widgets/ProtectedRoute/ui/InactivityTracker.tsx
  yarn.lock
Labels: Feature, Do not merge, Done

#258 [M2-3715] Fix: remove always available time label
  src/entities/activity/lib/types/activity.ts
  src/entities/activity/ui/ActivityCard/TimeStatusLabel.tsx
  src/widgets/ActivityGroups/model/factories/ActivityGroupsBuilder.ts
Labels: Bug, Done

#259 [M2-3756] Fix: conditional logic
  src/entities/activity/model/hooks/useActivityEventProgressState.ts
  src/entities/activity/model/hooks/useStepperState.ts
  src/shared/ui/CardItem/CardItem.tsx
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
Labels: Bug, Done

#260 [M2-3711] Fix: default color when input was autofilled
  src/app/index.css
  src/widgets/ActivityDetails/ui/ActivityMetaData.tsx
Labels: Bug, Done

#261 Dev cycle 0
  src/app/index.css
  src/entities/activity/lib/types/activity.ts
  src/entities/activity/model/hooks/useActivityEventProgressState.ts
  src/entities/activity/model/hooks/useStepperState.ts
  src/entities/activity/ui/ActivityCard/ActivityLabel/ActivityAvailableLabel.tsx
  src/entities/activity/ui/ActivityCard/TimeStatusLabel.tsx
  src/entities/activity/ui/items/TextItem.tsx
  src/entities/user/model/hooks/index.ts
  src/entities/user/model/hooks/useOnLogin.ts
  src/features/ForgotPassword/ui/ForgotPasswordForm.tsx
  src/features/Login/ui/LoginForm.tsx
  src/features/SaveAssessmentAndExit/index.tsx
  src/features/Signup/ui/SignupForm.tsx
  src/i18n/en/translation.json
  src/i18n/fr/translation.json
  src/pages/Login/index.tsx
  src/pages/Signup/index.tsx
  src/shared/ui/BaseButton/index.tsx
  src/shared/ui/CardItem/CardItem.tsx
  src/shared/ui/Markdown/lib/markdown-builder.ts
  src/widgets/ActivityDetails/ui/ActivityMetaData.tsx
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
  src/widgets/ActivityGroups/model/factories/ActivityGroupsBuilder.ts
  src/widgets/ActivityGroups/ui/ActivityGroupList.tsx
Labels: Bug, Done

#262 fix: app layout
  src/app/index.css
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
  src/widgets/AppLayout/index.tsx
Labels: Bug, Done

#263 Dev cycle 0
  src/app/index.css
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
  src/widgets/AppLayout/index.tsx
Labels: Bug, Done

#264 [M2-3762] Feature: slider animation and auto forward for SingleSelect
  src/entities/activity/ui/ActivityCardItem.tsx
  src/shared/animations/index.ts
  src/shared/animations/slider-animation/index.tsx
  src/shared/animations/slider-animation/useSliderAnimation.ts
  src/shared/utils/hooks/index.ts
  src/shared/utils/hooks/usePrevious.ts
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
Labels: Feature, Done

#265 [M2-3763] Feature: Invitation page updates
  src/entities/applet/ui/AppletList.tsx
  src/entities/invitation/ui/Invitation.tsx
  src/entities/invitation/ui/InvitationContent.tsx
  src/entities/invitation/ui/InvitationHeader.tsx
  src/entities/invitation/ui/style.scss
  src/features/InvitationAccept/ui/InvitationAcceptButton.tsx
  src/features/InvitationDecline/ui/InvitationDeclineButton.tsx
  src/features/SaveAssessmentAndExit/index.tsx
  src/shared/ui/BaseButton/index.tsx
  src/shared/ui/DisableOverlay/index.tsx
  src/shared/ui/DisableOverlay/style.scss
  src/shared/ui/Items/AudioPlayer/ui/AudioPlayerDuration.tsx
  src/shared/ui/PageMessage/index.tsx
  src/shared/ui/Text/index.tsx
  src/shared/ui/Typography/index.ts
  src/shared/ui/index.ts
  src/widgets/ActivityDetails/ui/AssessmentLayoutHeader.tsx
  src/widgets/ActivityDetails/ui/AssessmentWelcomeScreen.tsx
  src/widgets/FetchInvitation/ui/FetchInvitation.tsx
Labels: Feature, Done

#266 fix(markdown): Added preprocessor that removes redundant postfix from image links
  src/entities/activity/lib/markdownVariableReplacer.ts
Labels: Bug, Done

#267 Dev cycle 0
  src/entities/activity/ui/ActivityCardItem.tsx
  src/entities/applet/ui/AppletList.tsx
  src/entities/invitation/ui/Invitation.tsx
  src/entities/invitation/ui/InvitationContent.tsx
  src/entities/invitation/ui/InvitationHeader.tsx
  src/entities/invitation/ui/style.scss
  src/features/InvitationAccept/ui/InvitationAcceptButton.tsx
  src/features/InvitationDecline/ui/InvitationDeclineButton.tsx
  src/features/SaveAssessmentAndExit/index.tsx
  src/shared/animations/index.ts
  src/shared/animations/slider-animation/index.tsx
  src/shared/animations/slider-animation/useSliderAnimation.ts
  src/shared/ui/BaseButton/index.tsx
  src/shared/ui/DisableOverlay/index.tsx
  src/shared/ui/DisableOverlay/style.scss
  src/shared/ui/Items/AudioPlayer/ui/AudioPlayerDuration.tsx
  src/shared/ui/PageMessage/index.tsx
  src/shared/ui/Text/index.tsx
  src/shared/ui/Typography/index.ts
  src/shared/ui/index.ts
  src/shared/utils/hooks/index.ts
  src/shared/utils/hooks/usePrevious.ts
  src/widgets/ActivityDetails/ui/AssessmentLayoutHeader.tsx
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
  src/widgets/ActivityDetails/ui/AssessmentWelcomeScreen.tsx
  src/widgets/FetchInvitation/ui/FetchInvitation.tsx
Labels: Feature, Done

#269 [M2-3953] Fix: Disable auto-forward feature for last item in assessment
  src/widgets/ActivityDetails/model/index.ts
  src/widgets/ActivityDetails/model/validateItem.ts
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
Labels: Bug, Do not merge, Done

#270 Dev cycle 0
  src/widgets/ActivityDetails/model/index.ts
  src/widgets/ActivityDetails/model/validateItem.ts
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
Labels: Bug, Done
