Repository ChildMindInstitute/mindlogger-web-refactor, pull requests merged in 2024-01, with the labels that each got.

#319 [no-task] Fix: slider animation
  src/shared/animations/slider-animation/index.tsx
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
Labels: Bug, Done

#321 [M2-4546] Fix: useAuthorization and data-testids for Activity flow welcome screen
  src/entities/user/model/hooks/index.ts
  src/entities/user/model/hooks/useAuthorization.ts
  src/features/StartAssessment/index.tsx
  src/pages/index.tsx
  src/widgets/ActivityDetails/ui/ActivityMetaData.tsx
  src/widgets/ActivityDetails/ui/AssessmentWelcomeScreen.tsx
  src/widgets/Header/ui/index.tsx
  src/widgets/ProtectedRoute/ui/InactivityTracker.tsx
  src/widgets/ProtectedRoute/ui/index.tsx
Labels: Bug, Done

#322 [M2-4536] Fix: data-testid for system message in the forms
  src/shared/ui/DisplaySystemMessage/index.tsx
Labels: Bug, Done

#323 [M2-4560] Fix: data-testids for new items
  src/entities/activity/ui/items/AudioPlayerItem.tsx
  src/entities/activity/ui/items/DateItem.tsx
  src/entities/activity/ui/items/TimeItem.tsx
  src/entities/activity/ui/items/TimeRangeItem.tsx
Labels: Bug, Done

#324 Merge changes from the dev-cycle-0 branch into stage-cycle-0
  src/entities/activity/ui/items/AudioPlayerItem.tsx
  src/entities/activity/ui/items/DateItem.tsx
  src/entities/activity/ui/items/TimeItem.tsx
  src/entities/activity/ui/items/TimeRangeItem.tsx
  src/entities/user/model/hooks/index.ts
  src/entities/user/model/hooks/useAuthorization.ts
  src/features/StartAssessment/index.tsx
  src/pages/index.tsx
  src/shared/ui/DisplaySystemMessage/index.tsx
  src/widgets/ActivityDetails/ui/ActivityMetaData.tsx
  src/widgets/ActivityDetails/ui/AssessmentWelcomeScreen.tsx
  src/widgets/Header/ui/index.tsx
  src/widgets/ProtectedRoute/ui/InactivityTracker.tsx
  src/widgets/ProtectedRoute/ui/index.tsx
Labels: Bug, Done

#325 [M2-4590] Fix: unsupportable flow validation
  src/abstract/lib/index.ts
  src/abstract/lib/openStoreLink.ts
  src/entities/activity/api/useActivitiesByIdsQuery.ts
  src/entities/activity/lib/hooks/useActivitiesByIds.ts
  src/widgets/ActivityGroups/ui/ActivityCard/index.tsx
Labels: Bug, Done

#326 Merge change from the dev-cycle-0 branch into stage-cycle-0
  src/abstract/lib/index.ts
  src/abstract/lib/openStoreLink.ts
  src/entities/activity/api/useActivitiesByIdsQuery.ts
  src/entities/activity/lib/hooks/useActivitiesByIds.ts
  src/widgets/ActivityGroups/ui/ActivityCard/index.tsx
Labels: Bug, Done

#329 [M2-4570] Fix 2.5: TimeRange answer type
  src/shared/api/types/activity.ts
  src/widgets/ActivityDetails/model/mappers.ts
Labels: Bug, Done

#330 [M2-4560] Fix: data-testids for time range
  src/entities/activity/ui/items/TimeRangeItem.tsx
Labels: Bug, Done

#331 [M2-4580] Fix 2.5: Time / Date / TimeRange validation
  src/shared/utils/convert/date/index.ts
  src/shared/utils/convert/date/toDayMonthYear.ts
  src/shared/utils/convert/date/toDayMonthYearDTO.ts
  src/shared/utils/convert/date/toHourMinute.ts
  src/shared/utils/convert/date/toHourMinuteDTO.ts
  src/widgets/ActivityDetails/model/mappers.ts
  src/widgets/ActivityDetails/model/validateItem.ts
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
Labels: Bug, Done

#332 Merge changes from the dev-cycle-0 branch into stage-cycle-0
  src/entities/activity/ui/items/TimeRangeItem.tsx
  src/shared/api/types/activity.ts
  src/shared/utils/convert/date/index.ts
  src/shared/utils/convert/date/toDayMonthYear.ts
  src/shared/utils/convert/date/toDayMonthYearDTO.ts
  src/shared/utils/convert/date/toHourMinute.ts
  src/shared/utils/convert/date/toHourMinuteDTO.ts
  src/widgets/ActivityDetails/model/mappers.ts
  src/widgets/ActivityDetails/model/validateItem.ts
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
Labels: Bug, Done

#327 Merge changes from dev branch into stage
  index.html
  public/manifest.json
  src/abstract/lib/types/entityProgress.ts
  src/entities/activity/model/activity.slice.ts
  src/entities/activity/model/types.ts
  src/features/Logout/lib/useLogout.ts
  src/features/Signup/ui/SignupForm.tsx
  src/shared/utils/mixpanel.ts
  src/widgets/ActivityGroups/model/factories/AvailableGroupEvaluator.ts
  src/widgets/ActivityGroups/model/factories/GroupUtility.ts
  src/widgets/ActivityGroups/model/factories/ScheduledGroupEvaluator.ts
  src/widgets/ActivityGroups/model/hooks/useActivityGroup.ts
  src/widgets/ActivityGroups/model/hooks/useCompletedEntitiesBuilder.ts
  src/widgets/ActivityGroups/ui/ActivityGroupList.tsx
Labels: Done

#336 Merge changes from the dev-cycle-0 branch into stage-cycle-0
  src/shared/utils/convert/date/toHourMinute.ts
Labels: Bug, Done

#337 [M2-4787, M2-4774, M2-4778, M2-4777, M2-4776, M2-4775] Fix2.5: Small fixes
  html-scripts.js
  src/entities/activity/ui/ActivityCardItem.tsx
  src/features/SaveAssessmentAndExit/index.tsx
  src/shared/constants/theme.ts
  src/shared/ui/BaseButton/index.tsx
  src/shared/ui/Items/Checkbox/BaseCheckboxIcon.tsx
  src/shared/ui/NotificationCenter/ui/ErrorNotification.tsx
  src/shared/ui/NotificationCenter/ui/Notification.tsx
  src/shared/ui/NotificationCenter/ui/NotificationAnimation.tsx
  src/shared/ui/NotificationCenter/ui/SuccessNotification.tsx
  src/shared/ui/NotificationCenter/ui/WarningNotification.tsx
  src/widgets/ActivityDetails/ui/AssessmentLayoutHeader.tsx
  vite.config.ts
Labels: Bug, Done

#338 Merge changes from the dev-cycle-0 branch into stage-cycle-0
  html-scripts.js
  src/entities/activity/ui/ActivityCardItem.tsx
  src/features/SaveAssessmentAndExit/index.tsx
  src/shared/constants/theme.ts
  src/shared/ui/BaseButton/index.tsx
  src/shared/ui/Items/Checkbox/BaseCheckboxIcon.tsx
  src/shared/ui/NotificationCenter/ui/ErrorNotification.tsx
  src/shared/ui/NotificationCenter/ui/Notification.tsx
  src/shared/ui/NotificationCenter/ui/NotificationAnimation.tsx
  src/shared/ui/NotificationCenter/ui/SuccessNotification.tsx
  src/shared/ui/NotificationCenter/ui/WarningNotification.tsx
  src/widgets/ActivityDetails/ui/AssessmentLayoutHeader.tsx
  vite.config.ts
Labels: Bug, Done

#339 [M2-4783] Feature: vitest setup / eslint upgrade / code style fixes
  .gitignore
  .nvmrc
  package.json
  src/app/index.css
  src/entities/activity/lib/types/activity.ts
  src/entities/activity/lib/types/item.ts
  src/entities/activity/ui/items/CheckboxItem/index.tsx
  src/entities/activity/ui/items/ItemPicker.tsx
  src/entities/activity/ui/items/RadioItem/index.tsx
  src/entities/applet/lib/mapper.ts
  src/entities/applet/ui/AppletList.tsx
  src/entities/invitation/ui/Invitation.tsx
  src/entities/user/model/hooks/useAuthorization.ts
  src/entities/user/model/hooks/useOnLogin.ts
  src/features/language/ui/LanguageDropdown.tsx
  src/pages/index.tsx
  src/shared/api/services/activity.service.ts
  src/shared/api/services/applet.service.ts
  src/shared/api/services/authorization.service.ts
  src/shared/api/services/axios.ts
  src/shared/api/services/events.service.ts
  src/shared/api/services/invitation.service.ts
  src/shared/api/types/activity.ts
  src/shared/api/types/applet.ts
  src/shared/api/types/events.ts
  src/shared/api/types/item.ts
  src/shared/ui/Items/AudioPlayer/ui/AudioPlayerBase.tsx
  src/shared/ui/Markdown/style.css
  src/shared/ui/NotificationCenter/ui/Notification.tsx
  src/shared/ui/NotificationCenter/ui/NotificationAnimation.tsx
  src/shared/ui/NotificationCenter/ui/NotificationCenter.tsx
  src/shared/utils/string/getFirstLetter.test.ts
  src/test/setup.ts
  src/widgets/ActivityDetails/ui/ActivityDetails.tsx
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
  src/widgets/ActivityDetails/ui/AssessmentWelcomeScreen.tsx
  src/widgets/ActivityGroups/model/factories/ActivityGroupsBuilder.ts
  src/widgets/ActivityGroups/model/factories/AvailableGroupEvaluator.ts
  src/widgets/ActivityGroups/model/factories/ListItemsFactory.ts
  src/widgets/ActivityGroups/model/factories/ScheduledGroupEvaluator.ts
  src/widgets/ActivityGroups/ui/ActivityCard/index.tsx
  src/widgets/ActivityGroups/ui/ActivityCardList.tsx
  src/widgets/ActivityGroups/ui/ActivityGroup.tsx
  src/widgets/ActivityGroups/ui/ActivityGroupList.tsx
  src/widgets/ActivityGroups/ui/ActivityGroups.tsx
  src/widgets/FetchInvitation/ui/FetchInvitation.tsx
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: Feature, Done

#340 Husky pre-commit hooks updates
  .husky/pre-commit
  src/shared/utils/convert/date/toDayMonthYear.test.ts
Labels: Feature, Done

#341 [M2-4784] Feature: ActivityGroupBuilder unit test
  package.json
  src/abstract/lib/types/event.ts
  src/abstract/lib/types/index.ts
  src/entities/event/lib/types/event.ts
  src/entities/event/model/mappers.ts
  src/test/vitest.setup.ts
  src/widgets/ActivityGroups/model/factories/ActivityGroupsBuilder.test.ts
  src/widgets/ActivityGroups/model/factories/AvailableGroupBuilder.test.ts
  src/widgets/ActivityGroups/model/factories/ScheduledGroupEvaluator.test.ts
  tsconfig.node.json
  vite.config.js
  vite.config.ts
  yarn.lock
Labels: Feature, Done

#342 [M2-4811] Feature: encryption tests
  .gitignore
  .nvmrc
  package.json
  src/crypto-browserify.d.ts
  src/entities/activity/lib/hooks/useEncryptPayload.ts
  src/env.d.ts
  src/shared/api/services/axios.ts
  src/shared/constants/environment.variables.ts
  src/shared/constants/index.ts
  src/shared/utils/encryption/encryption.test.ts
  src/shared/utils/encryption/encryption.ts
  src/shared/utils/encryption/mockData.ts
  src/shared/utils/hooks/useEncryption.ts
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: Feature, Done

#343 [M2-4792] Feature: Transfer Ownership Updates
  src/features/TransferOwnershipAccept/ui/TransferOwnershipAccept.tsx
  src/features/TransferOwnershipDecline/ui/TransfetOwnershipDecline.tsx
  src/i18n/en/translation.json
  src/i18n/fr/translation.json
Labels: Feature, In progress

#347 [M2-4818] Feature: AutoAdvance setting for SingleSelect
  src/entities/activity/lib/types/item.ts
  src/shared/api/types/item.ts
  src/widgets/ActivityDetails/model/hooks/useAutoForward.ts
Labels: Feature, Done

#348 [M2-4733] Fix 2.5: Hide Badge settings for Activity Flow
  src/widgets/ActivityGroups/lib/activityGroupsBuilder.ts
  src/widgets/ActivityGroups/lib/types.ts
  src/widgets/ActivityGroups/model/factories/ActivityGroupsBuilder.test.ts
  src/widgets/ActivityGroups/model/factories/AvailableGroupBuilder.test.ts
  src/widgets/ActivityGroups/model/factories/ListItemsFactory.ts
  src/widgets/ActivityGroups/model/factories/ScheduledGroupEvaluator.test.ts
  src/widgets/ActivityGroups/model/hooks/useEntityCardDetails.ts
  src/widgets/ActivityGroups/model/mappers.ts
  src/widgets/ActivityGroups/ui/ActivityCard/index.tsx
Labels: Bug, Done

#349 [M2-3443] Fix-2.5: due info for inProgress cards
  src/widgets/ActivityGroups/model/factories/ActivityGroupsBuilder.test.ts
  src/widgets/ActivityGroups/model/factories/ListItemsFactory.ts
  src/widgets/ActivityGroups/ui/ActivityCard/TimeStatusLabel.tsx
Labels: Bug, Done

#350 [M2-4857] Tests: audio player
  src/shared/ui/Items/AudioPlayer/ui/AudioPlayerBase.tsx
  src/shared/ui/Items/AudioPlayer/ui/AudioPlayerControls.tsx
  src/shared/ui/Items/AudioPlayer/ui/AudioPlayerDuration.tsx
  src/shared/ui/Items/AudioPlayer/ui/AudioPlayerVolume.tsx
  src/shared/ui/Items/AudioPlayer/ui/AudipPlayerProgressBar.tsx
Labels: Feature, Done

#352 [M2-4773][M2-4887] Fix-2.5: Youtube Videos, Images, Videos supports in WYSIWYG
  src/shared/ui/Markdown/lib/Vimeo.builder.test.ts
  src/shared/ui/Markdown/lib/Vimeo.builder.ts
  src/shared/ui/Markdown/lib/YouTube.builder.test.ts
  src/shared/ui/Markdown/lib/YouTube.builder.ts
  src/shared/ui/Markdown/lib/markdown-builder.ts
  src/shared/ui/Markdown/style.css
  src/shared/utils/helpers/getInitials.ts
Labels: Feature, Done

#355 Merge changes into stage2.5 branch from the dev2.5
  src/entities/activity/lib/types/item.ts
  src/shared/api/types/activity.ts
  src/shared/api/types/item.ts
  src/shared/ui/Items/AudioPlayer/ui/AudioPlayerBase.tsx
  src/shared/ui/Items/AudioPlayer/ui/AudioPlayerControls.tsx
  src/shared/ui/Items/AudioPlayer/ui/AudioPlayerDuration.tsx
  src/shared/ui/Items/AudioPlayer/ui/AudioPlayerVolume.tsx
  src/shared/ui/Items/AudioPlayer/ui/AudipPlayerProgressBar.tsx
  src/shared/ui/Markdown/lib/Vimeo.builder.test.ts
  src/shared/ui/Markdown/lib/Vimeo.builder.ts
  src/shared/ui/Markdown/lib/YouTube.builder.test.ts
  src/shared/ui/Markdown/lib/YouTube.builder.ts
  src/shared/ui/Markdown/lib/markdown-builder.ts
  src/shared/ui/Markdown/style.css
  src/shared/utils/convert/date/toHourMinute.ts
  src/shared/utils/helpers/getInitials.ts
  src/widgets/ActivityDetails/model/hooks/useAutoForward.ts
  src/widgets/ActivityDetails/model/mappers.ts
  src/widgets/ActivityGroups/lib/activityGroupsBuilder.ts
  src/widgets/ActivityGroups/lib/types.ts
  src/widgets/ActivityGroups/model/factories/ActivityGroupsBuilder.test.ts
  src/widgets/ActivityGroups/model/factories/AvailableGroupBuilder.test.ts
  src/widgets/ActivityGroups/model/factories/ListItemsFactory.ts
  src/widgets/ActivityGroups/model/factories/ScheduledGroupEvaluator.test.ts
  src/widgets/ActivityGroups/model/hooks/useEntityCardDetails.ts
  src/widgets/ActivityGroups/model/mappers.ts
  src/widgets/ActivityGroups/ui/ActivityCard/TimeStatusLabel.tsx
  src/widgets/ActivityGroups/ui/ActivityCard/index.tsx
Labels: Feature, Done

#357 [M2-4887] Feature: new header
  src/shared/api/services/axios.ts
Labels: Feature, Done

#359 M2-4834: Adding github action workflow to run tests on pull requests
  .github/workflows/tests.yml
Labels: Feature, Done

#360 M2-4826: Update forgot password expired/invalid link message
  src/i18n/en/translation.json
  src/i18n/fr/translation.json
  src/pages/RecoveryPassword/index.tsx
Labels: Feature, Done
