Repository ChildMindInstitute/mindlogger-web-refactor, pull requests merged in 2024-03, with the labels that each got.

#399 M2-3613 Button height
  src/features/ForgotPassword/ui/ForgotPasswordForm.tsx
Labels: Bug, Done

#400 M2-3614 Change dropdown font from Roboto to Atkinson
  src/pages/Profile/index.tsx
  src/pages/Settings/index.tsx
  src/shared/ui/Dropdown/ui/index.tsx
  src/widgets/Footer/index.tsx
Labels: Bug, Done

#401 Fix button width on the assessment page
  src/entities/activity/ui/ItemCardButtons.tsx
Labels: Bug, Done

#398 M2-5512: updates PR template format
  .github/pull_request_template.md
Labels: Done, Enhancement

#402 M2-5548 [Web app 2.5] Public link without the required account: error when sending responses for Activity Flow
  src/shared/constants/routes.ts
Labels: Bug, Done

#403 M2-5015 Message item: Not all formatting options of WYSIWYG component are supported
  src/shared/ui/Markdown/lib/markdown-builder.ts
  src/shared/ui/Markdown/lib/validateAudio.ts
  src/shared/ui/Markdown/style.css
Labels: Bug, Done

#404 M2-5060 Change logic of monthly event calculation
  src/abstract/lib/GroupBuilder/AvailableGroupBuilder.test.ts
  src/abstract/lib/GroupBuilder/AvailableGroupEvaluator.ts
  src/abstract/lib/GroupBuilder/GroupUtility.ts
  src/abstract/lib/GroupBuilder/ScheduledGroupEvaluator.test.ts
  src/entities/event/model/operations/ScheduledDateCalculator.monthly.test.ts
  src/entities/event/model/operations/ScheduledDateCalculator.ts
Labels: Bug, Done

#405 SYNC: Merge Release/v2.1.1 into master
  .env.example
  .gitignore
  Jenkinsfile.groovy
  src/entities/applet/ui/AppletCard.tsx
  src/features/PrivateJoinAccept/ui/PrivateJoinAcceptButton.tsx
  src/features/TransferOwnershipAccept/ui/TransferOwnershipAccept.tsx
  src/shared/api/types/invitation.ts
  src/shared/utils/analytics/analyticsService.ts
  src/shared/utils/analytics/index.ts
  src/shared/utils/analytics/mixpanel.ts
  src/shared/utils/index.ts
  src/widgets/ActivityDetails/model/hooks/useSubmitAnswersMutation.ts
  src/widgets/ActivityGroups/model/hooks/useStartEntity.ts
  src/widgets/ActivityGroups/ui/ActivityCard/index.tsx
  src/widgets/FetchInvitation/ui/FetchPrivateInvitation.tsx
Labels: Done

#407 [M2-5266] Changed the notification center behavior
  src/shared/constants/theme.ts
  src/shared/ui/NotificationCenter/ui/ErrorNotification.tsx
  src/shared/ui/NotificationCenter/ui/Notification.tsx
  src/shared/ui/NotificationCenter/ui/NotificationAnimation.tsx
  src/shared/ui/NotificationCenter/ui/NotificationCenter.tsx
  src/shared/ui/NotificationCenter/ui/SuccessNotification.tsx
  src/shared/ui/NotificationCenter/ui/WarningNotification.tsx
  src/shared/utils/hooks/index.ts
  src/shared/utils/hooks/useIntersectionObserver.ts
Labels: Bug, Done

#409 [M2-3614] Change all component`s font to Atkinson
  src/features/Signup/ui/SignupForm.tsx
  src/shared/ui/BaseButton/index.tsx
  src/shared/ui/Card/index.tsx
  src/shared/ui/Input/index.tsx
  src/shared/ui/Text/index.tsx
  src/widgets/Header/ui/LoginButton.tsx
Labels: Done

#411 [M2-4772] Slider refinements
  src/entities/activity/ui/items/SliderItem.tsx
  src/shared/ui/Items/Slider/index.tsx
  src/shared/ui/Items/Slider/style.css
Labels: Done, Enhancement

#412 [M2-3437] Change the regex for extracting params from media link
  src/shared/ui/Markdown/lib/extractDataFromMediaLink.ts
  src/shared/ui/Markdown/lib/markdown-builder.ts
  src/shared/ui/Markdown/lib/useMarkdownExtender.ts
Labels: Bug, Done

#413 [M2-3614] Fix font on the Reset Password page
  src/pages/ForgotPassword/index.tsx
Labels: Bug, Done

#414 [M2-2644] Feature: MultiSelectMatrix Config DTO was added
  src/abstract/lib/constants.ts
  src/abstract/lib/types/index.ts
  src/abstract/lib/types/item.ts
  src/app/App.tsx
  src/entities/activity/lib/hooks/useTextVariablesReplacer.ts
  src/entities/activity/lib/markdownVariableReplacer.ts
  src/entities/activity/lib/types/item.ts
  src/entities/activity/ui/ActivityCardItem.tsx
  src/entities/activity/ui/items/CheckboxItem/index.tsx
  src/entities/activity/ui/items/ItemPicker.tsx
  src/entities/activity/ui/items/MatrixCheckboxItem/AxisListItem.tsx
  src/entities/activity/ui/items/MatrixCheckboxItem/MatrixCell.tsx
  src/entities/activity/ui/items/MatrixCheckboxItem/MatrixHeader.tsx
  src/entities/activity/ui/items/MatrixCheckboxItem/MatrixRow.tsx
  src/entities/activity/ui/items/MatrixCheckboxItem/StackedItemsGrid.tsx
  src/entities/activity/ui/items/MatrixCheckboxItem/index.tsx
  src/entities/applet/model/ConditionalLogicBuilder.ts
  src/entities/applet/model/hooks/useSaveActivityItemAnswer.ts
  src/entities/applet/model/mapper.ts
  src/entities/applet/model/types.ts
  src/shared/api/types/activity.ts
  src/shared/api/types/item.ts
  src/shared/constants/theme.ts
  src/shared/ui/Avatar/index.tsx
  src/shared/ui/Items/SelectBase/SelectBaseBox.tsx
  src/shared/ui/Logo/index.tsx
  src/shared/utils/helpers/getInitials.ts
  src/shared/utils/hooks/useCustomMediaQuery.ts
  src/widgets/ActivityDetails/model/getFirstResponseDataIdentifierTextItem.ts
  src/widgets/ActivityDetails/model/mappers.ts
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
  src/widgets/ActivityGroups/ui/ActivityCard/ActivityCardIcon.tsx
Labels: Feature, Done

#417 [M2-6058] Enable mixpanel for UAT env
  src/env.d.ts
  src/shared/utils/analytics/mixpanel.ts
Labels: Done, Enhancement

#419 [M2-6081] Change the logic how to highlight the selected value
  src/shared/ui/Items/Slider/index.tsx
Labels: Bug, Done
