Repository ChildMindInstitute/mindlogger-web-refactor, pull requests merged in 2024-02, with the labels that each got.

#362 Add PR template
  .github/pull_request_template.md
Labels: Feature, Done

#356 [M2-4833] Feature: Additional text response
  src/entities/activity/lib/helpers.test.ts
  src/entities/activity/lib/helpers.ts
  src/entities/activity/lib/types/item.ts
  src/entities/activity/ui/ActivityCardItem.tsx
  src/entities/activity/ui/AdditionalTextResponse.tsx
  src/entities/activity/ui/index.ts
  src/entities/applet/model/hooks/useSaveActivityItemAnswer.ts
  src/entities/applet/model/hooks/useUserEvents.ts
  src/entities/applet/model/mapper.ts
  src/entities/applet/model/slice.ts
  src/entities/applet/model/types.ts
  src/i18n/en/translation.json
  src/i18n/fr/translation.json
  src/shared/api/types/item.ts
  src/widgets/ActivityDetails/model/hooks/useAutoForward.ts
  src/widgets/ActivityDetails/model/mappers.ts
  src/widgets/ActivityDetails/model/validateItem.ts
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
Labels: Feature, In progress

#358 [M2-4788] Feature: "Next" button behavior update
  src/i18n/en/translation.json
  src/i18n/fr/translation.json
  src/shared/ui/BaseButton/index.tsx
  src/shared/ui/BootstrapModal/index.tsx
  src/shared/ui/MuiModal/index.tsx
  src/shared/ui/index.ts
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
  src/widgets/ActivityGroups/ui/ActivityGroupList.tsx
Labels: Feature, Done

#364 [M2-5048] Feature: isNoneAbove for MultiSelectItem
  src/entities/activity/lib/types/item.ts
  src/entities/activity/ui/items/CheckboxItem/index.tsx
  src/shared/api/types/item.ts
Labels: Feature, Done

#365 AutoCompletion feature preparation
  src/abstract/lib/getProgressId.ts
  src/entities/event/api/index.ts
  src/entities/event/api/useUserEventsMutation.ts
  src/shared/api/services/events.service.ts
  src/shared/api/types/applet.ts
  src/shared/api/types/events.ts
  src/shared/utils/index.ts
  src/shared/utils/matchPaths.ts
  src/shared/utils/useTimer.ts
  src/widgets/ProtectedRoute/InactivityTracker.tsx
Labels: Feature, Done

#366 GroupBuilder Refactor
  src/abstract/lib/GroupBuilder/ActivityGroupsBuilder.test.ts
  src/abstract/lib/GroupBuilder/ActivityGroupsBuilder.ts
  src/abstract/lib/GroupBuilder/AvailableGroupBuilder.test.ts
  src/abstract/lib/GroupBuilder/AvailableGroupEvaluator.ts
  src/abstract/lib/GroupBuilder/GroupUtility.ts
  src/abstract/lib/GroupBuilder/ListItemsFactory.ts
  src/abstract/lib/GroupBuilder/ScheduledGroupEvaluator.test.ts
  src/abstract/lib/GroupBuilder/ScheduledGroupEvaluator.ts
  src/abstract/lib/GroupBuilder/activityGroups.types.ts
  src/abstract/lib/GroupBuilder/index.ts
  src/abstract/lib/GroupBuilder/types.ts
  src/widgets/ActivityGroups/lib/index.ts
  src/widgets/ActivityGroups/lib/types.ts
  src/widgets/ActivityGroups/model/hooks/useActivityGroup.ts
  src/widgets/ActivityGroups/model/hooks/useEntityCardDetails.ts
  src/widgets/ActivityGroups/model/hooks/useStartEntity.ts
  src/widgets/ActivityGroups/model/mappers.ts
  src/widgets/ActivityGroups/model/services/ActivityGroupsBuildManager.ts
  src/widgets/ActivityGroups/ui/ActivityCard/TimeStatusLabel.tsx
  src/widgets/ActivityGroups/ui/ActivityCard/index.tsx
  src/widgets/ActivityGroups/ui/ActivityCardList.tsx
  src/widgets/ActivityGroups/ui/ActivityGroup.tsx
Labels: Feature, Done

#379 M2-5022: preventing user to skip the audio player if it is not skippable
  src/entities/activity/ui/items/AudioPlayerItem.tsx
  src/entities/activity/ui/items/ItemPicker.tsx
  src/entities/applet/model/mapper.ts
  src/entities/applet/model/types.ts
  src/i18n/en/translation.json
  src/i18n/fr/translation.json
  src/shared/api/types/activity.ts
  src/shared/ui/Items/AudioPlayer/lib/constants.ts
  src/shared/ui/Items/AudioPlayer/lib/index.ts
  src/shared/ui/Items/AudioPlayer/ui/AudioPlayerBase.tsx
  src/widgets/ActivityDetails/model/mappers.ts
  src/widgets/ActivityDetails/model/validateItem.ts
Labels: Feature, Done

#377 M2-5293: validating date and time items values before passing to activityProgress, bug fixes
  src/entities/applet/model/mapper.ts
  src/shared/ui/Items/Date/index.tsx
  src/shared/ui/Items/Time/index.tsx
Labels: Done

#380 M2-5011 Feature: Update year in the footer
  src/entities/applet/model/hooks/useSaveActivityItemAnswer.ts
  src/widgets/ActivityGroups/ui/ActivityCard/ActivityCardBase.tsx
  src/widgets/Footer/index.tsx
Labels: Feature, Done

#372 Fixed isNoneAbove business logic
  src/entities/activity/ui/items/CheckboxItem/index.tsx
Labels: Done

#382 Fix imports after merge
  src/widgets/ActivityGroups/ui/ActivityCard/ActivityCardRestartResume.tsx
Labels: Bug, Done

#383 M2-5203 Fix: Submit popup text
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
Labels: Bug, Done

#388 Set all overflows to auto
  src/shared/ui/Card/index.tsx
  src/widgets/ActivityDetails/ui/AssessmentLoadingScreen.tsx
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
  src/widgets/ActivityGroups/ui/ActivityGroupList.tsx
  src/widgets/AppLayout/index.tsx
Labels: Bug, Done

#387 hotfix: Set all overflow settings to auto
  src/shared/ui/Card/index.tsx
  src/widgets/ActivityDetails/ui/AssessmentLoadingScreen.tsx
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
  src/widgets/ActivityGroups/ui/ActivityCard/ActivityCardTitle.tsx
  src/widgets/ActivityGroups/ui/ActivityGroupList.tsx
  src/widgets/AppLayout/index.tsx
Labels: Bug, Done

#373 M2-4827: Post password reset redirection
  src/features/RecoveryPassword/ui/RecoveryPasswordForm.tsx
  src/i18n/en/translation.json
  src/i18n/fr/translation.json
  src/pages/Login/index.tsx
  src/shared/ui/NotificationCenter/lib/useNotification.ts
  src/shared/utils/hooks/index.ts
  src/shared/utils/hooks/useOnceEffect.ts
Labels: Feature, Done

#386 M2-5304 Fix: Notification appears twice on the assessment page
  src/widgets/ActivityDetails/ui/AssessmentLayout.tsx
  src/widgets/ActivityDetails/ui/AssessmentLoadingScreen.tsx
  src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
  src/widgets/ActivityDetails/ui/AssessmentWelcomeScreen.tsx
Labels: Bug, Done

#389 M2-5376: add `LICENSE.md`
  LICENSE.md
  README.md
Labels: Done, Enhancement

#392 M2-5202: add missing `.env.example`
  .env.example
  .gitignore
Labels: Bug

#393 M2-4993 Mixpanel Tracking: Assessment Resume/Restart
  src/widgets/ActivityGroups/ui/ActivityCard/index.tsx
Labels: Done, Enhancement

#394 M2-5077 [WEB] Mixpanel Tracking: Applet ID in event properties
  src/entities/applet/ui/AppletCard.tsx
  src/features/PrivateJoinAccept/ui/PrivateJoinAcceptButton.tsx
  src/features/TransferOwnershipAccept/ui/TransferOwnershipAccept.tsx
  src/shared/api/types/invitation.ts
  src/shared/utils/analytics/analyticsService.ts
  src/shared/utils/analytics/index.ts
  src/shared/utils/analytics/mixpanel.ts
  src/shared/utils/index.ts
  src/widgets/ActivityDetails/model/hooks/useSubmitAnswersMutation.ts
  src/widgets/ActivityGroups/model/hooks/useStartEntity.ts
  src/widgets/ActivityGroups/ui/ActivityCard/index.tsx
  src/widgets/FetchInvitation/ui/FetchPrivateInvitation.tsx
Labels: Done, Enhancement

#395 M2-5033 [Web] Mixpanel Tracking: Sumbit_id in event properties
  src/shared/utils/analytics/analyticsService.ts
  src/widgets/ActivityDetails/model/hooks/useSubmitAnswersMutation.ts
Labels: Done, Enhancement

#396 [No-task] Jenkins update
  Jenkinsfile.groovy
Labels: Done, Enhancement
